Display app version - task #73
HlidacStatu/Volicsky-Prukaz pull request #74
Opened 2019-05-04 10:34 UTC by KamilZm

@zzen @michalblaha 
Vyřešil jsem to tak, že se informaci o verzi bere ze souboru 'assets/files/appversion.txt'. Je to pro generování jednodušší, než něco vyměňovat v HTML souboru a také je to bezpečnější, protože nehrozí, že by se mohl index.html tím zásahem díky nějakému problému rozdrbat. 
@zzen Pošlete prosím @michalblaha info, jak zjistit hash commitu, který jde do produkce
@michalblaha Zjištěný hash prosím při publikování uložte do `assets/files/appversion.txt`
Jako výchozí je v `assets/files/appversion.txt` verze `000000100000000000000000000000000000000`, takže kdyby generování selhalo, zobrazí se ta (nebo žádná, pokud obsahem toho souboru nebude pouze SHA1).

2019-05-04 13:03 UTC, KamilZm commented
V #35e21455b6f1d85e76cde03a7fad66be2734f7823 přidáno scrollování na porvek formuláře po stisknutí tlačítka, aby se uživatel (hlavně v mobilní verzi) nedostal vždy na začátek stránky, protože to na mě působili strašně zmatečně (stiskl tlačítko a viděl zase od začátku to, co předtím).

2019-05-05 19:49 UTC, KamilZm commented
V commitu 50f1a6f kompletně předělány validace. Bohužel se mi zatím nepodařilo udělat rozumnou validaci na autocomplete PSČ - když se uživatel vrátí zpět z náhledu to blbě vypadá, protože se to tváří, že není položka vybraná, ale je, jen to autocomplete nezobrazuje, protože tam nemá žádný přiřazení objekt. Ale data jsou OK. 

Je to teď nachystané tak aby šel přidat i validační sumář. Ale úplně čisté řešení to není, lepší by bylo, kdyby se např. property v userdata nastavovaly přes setter a přímo se prováděla validace. Ale do toho jsem zatím nešel.

2019-05-06 19:04 UTC, KamilZm commented
V commitu fc5c9a8 je jako hlavní úprava pro zobrazování focusu+chyb u na PSČ a také opravena věc, která mě od začátku vadila - když se uživatel vrátil z náhledu, tak nezůstalo vyplněné PSČ. Teď už zůstane (resp. se automaticky vyplní na pozadí)

2019-05-08 13:32 UTC, KamilZm reviewed
V commitu 19519b6 jsem udělal velké změny, protože mě už nebavilo pořád paralelně udržovat  CZ a EN verzi formuláře, protože ta práce s položkami (input boxy, validace apod.) byla šílená. Teď je jen jedna, univerzální verze. Týká se to jen formuláře, ne obecně.  
Jazykově nezávislá část aplikace je ohraničena komentářem `fully independent part on selected language` tam to prosím držte a nepište dovnitř lokalizované texty.
Dále jsem udělal konfigurační soubor, kde jsou zatím data voleb.
Předělal jsem validace a už se umí zobrazit kompletní validační sumář nebo jen závažnější chyby s popisem (přepíná se to nastavuje v konfiguraci).
PS: Snažil jsem se kód komentovat, ale v EN nejsem moc silný..

2019-05-09 08:32 UTC, zzen commented
Kamile, build je rozbitý protože je potřeba přidat nové soubory appconfig.js. appconfig.txt do now.json konfigurace, např. takhle:

```    "builds": [
        { "src": "index.html", "use": "@now/static" },
        { "src": "appconfig.js", "use": "@now/static" },
        { "src": "appconfig.txt", "use": "@now/static" },
        { "src": "favicon.ico", "use": "@now/static" },
        { "src": "assets/**", "use": "@now/static" }
    ],```

2019-05-09 09:10 UTC, KamilZm commented
@zzen OK, omlouvám se a díky za vysvětlení, přidáno. 
Vrtalo mi teď hlavou, že jsem to nemusel dělat dříve, když jsem přidával soubory do `/assets/`, ale teď tam vidím `{ "src": "assets/**", "use": "@now/static" }`, čímž je to jasné.

2019-05-10 19:29 UTC, zzen requested changes
Kamile - pardon za neodeslání review… Poznámky jsou u jednotlivých řádek kódu ale ještě to v rychlosti shrnu:

1) je to opravdu velký pull-request a spojuje tam několik separátních vylepšení: nové validace, appversion/appconfig infrastrukturu a sloučení en/cz verze formuláře. Pro příště bych doporučoval posílat jako separátní pull-requesty - pak se nestane, že více komplikované/kontroverzní změny jako třeba ty validace+refaktoring jazykové mutace nezablokují malé a triviální změny co už dávno mohly být nasazené - jako třeba ten appversion.txt

2) z appconfig.js mám fakt radost, tak jsem to také chtěl udělat (mít explicitní konfiguraci těch variabilních dat) aby se to hezky dalo udržovat dále do budoucna. Ale vadí mi tam, že jsme snižili uživatelskou přívětivost aplikace a tak mám komentáře k formátování těch dat. Je tam už velmi flexibilní knihovna moment.js používaná na formátování datumů/času na jiných místech, doporučuju vyřešit tímto

3) z validací jsem trochu rozpačitý, protože v kombinaci s tím sloučením EN/CZ verze do lokalizovaných textu celou záležitost dost výrazně zkomplikovaly. Navíc je to nekonzistentní (sloučené jsou jen ty dvě formulářové stránky, /preview je stále ještě duální jestli na to správně koukám). Z pohledu code-review mimo jiné hodnotím i jak je jednoduché ten kód přečíst/pochopit pro někoho "kdo přijde po nás" a tady jsme myslím refaktorem dost utrpěli.

Tolik ke shrnutí - detaily viz konkrétní řádky.

2019-05-10 19:29 UTC, zzen commented on index.html
> +                    <span>Volby do Evropského parlamentu se uskuteční ve dnech <strong>{{decoder(this.getVotingIntervalWithTime)}}</strong></span>
Kamile - není mi jasné, k čemu přesně slouží decoder (a &nbsp; znaky jsem nikde nenašel), nicméně výstup z tohoto formátování těch datumů je jiný než původní: `24. 5. 2019 (od 14:00 do 22:00) a 25 .5. 2019 (od 8:00 do 14:00)` vs `24.05.2019 (14:00-22:00) až 25.05.2019 (08:00-14:00)`. Doporučoval bych na to formátování dat použít ten moment.js který už v jiných místech aplikace použit je.

2019-05-10 19:29 UTC, zzen commented on index.html
> +                    <li><strong class="emphasized">osobně</strong><span> – dostavte se přímo na úřad s platným dokladem totožnosti nejpozději {{this.appConfig.votingCardRequestdeliveryLastTime.person
Kamile - to samé platí pro formátovací funkce tady - výstup je horší než co jsme tam měli předtím:

> platným dokladem totožnosti nejpozději 22. 5. 2019

vs

> platným dokladem totožnosti nejpozději 22.05.2019 16:00

(proč ten čas, nezáleží to na otvíracích hodinách úřadu? a pokud ano, měla bý tam být předložka `v`)

2019-05-10 19:29 UTC, zzen commented on index.html
> +                    <li><strong class="emphasized">písemně</strong><span> – žádost musíte úřadu doručit do {{this.appConfig.votingCardRequestdeliveryLastTime.post}}h pomocí vaší datové schránky nebo
to samé, předchozí verze:

> žádost musíte úřadu doručit do 17. 5. 2019 v 16:00

vs

> žádost musíte úřadu doručit do 17.05.2019 16:00h

(h nakonci, které navíc v předchozí řádce při uvedení času není, a tady bych ho také neuváděl)

2019-05-10 19:29 UTC, zzen commented on index.html
> +                    <li><strong class="emphasized">písemně</strong><span> – žádost musíte doručit do {{this.appConfig.votingCardRequestdeliveryLastTime.post}}h pomocí vaší datové schránky nebo poštou
ditto viz výše

2019-05-10 19:29 UTC, zzen commented on index.html
> +                    <li><strong class="emphasized">in person</strong><span> – directly at the office with valid ID no later than {{this.appConfig.votingCardRequestdeliveryLastTime.personal}}h,</span>
Kromě připomínek k formátování výše, zde bylo formátování data v anglosaské formě (22 May 2019), což popravdě mělo být 22nd May 2019. Opět doporučuju použít moment.js který tohle umí dělat za vás.

2019-05-10 19:29 UTC, zzen commented on index.html
> +                            {{texts['privacyInfo'][this.getLanguage()]}} <a href="assets/files/Zadost-Volicsky-Prukaz-EU2019-CR.pdf">{{texts['applicationTemplateDownloadLink'][this.getLanguage()]}}</
Kamile, já to původně také dělal formou textových lokalizací, ale pak jsem se po úvaze rozhodl to takhle nedělat, protože mi přijde, že zápory převažují nad klady. Je sice pravda, že při udržování aplikace je občas potřeba změny aplikovat dvakrát, nicméně zase je ten HTML blok relativně kompaktní a je relativně přehledné, jak se zobrazuje.

Pěkný příklad je v téhle ukázce. Původní znění bylo relativně uživatelsky přívětivé:

> Pokud chcete mít 100% jistotu, můžete se při vytváření žádosti odpojit od internetu nebo si stáhněte a vyplňte [šablonu žádosti]() ručně sami.

vs 

> Pokud chcete mít 100% jistotu, můžete se při vytváření žádosti odpojit od internetu nebo si žádost stáhněte a vyplňte ručně sami [(stažení šablony žádosti)]().

2019-05-10 19:29 UTC, zzen commented on index.html
> +                                    max-result-items="15" more-results-exists-text="(...upřesněte zadání...)" ref="autocompleteZIP"
lady máme příklad nezlokalizovaného textu který z české verze prolíná do anglické protože nemá překladovou funkci

2019-05-10 19:29 UTC, zzen commented on index.html
> +        function getDefaultDataObject(nullable, valid, caption, validator) {
Kamile - tohle mi přijde také obrovská změna kterou úplně nechápu - skoro celá aplikace je předělaná, kdekoliv je `userData` použito, tak tam na konci přibylo `.value`. Pak je yde `getDefaultDataObject()` a `getUserData()` - k čemu je celá tahle ceremonie dobrá?

2019-05-10 19:29 UTC, zzen commented on index.html
> +                    return this.$route.path == '/en/form' ? 'EN' : 'CZ';
jak tohle funguje? máme i `/en/preview` - to lokalizováno nebylo?

2019-05-10 19:48 UTC, KamilZm commented on index.html
> +                    <span>Volby do Evropského parlamentu se uskuteční ve dnech <strong>{{decoder(this.getVotingIntervalWithTime)}}</strong></span>
decoder je funkce zajišťující, aby se v {{ }} nezobrazovaly HTML entity ale aplikovaly se. Bez něj by tam bylo zobrazeno tohle (nechtěl jsem, aby se to mohlo zalomit v čase):
`24. 5. 2019 (14:00&nbsp;&#8209;&nbsp;22:00)` 
Moment.js - OK, stejně to na něj zrovna předělávám.

2019-05-10 19:49 UTC, KamilZm commented on index.html
> +                    <li><strong class="emphasized">osobně</strong><span> – dostavte se přímo na úřad s platným dokladem totožnosti nejpozději {{this.appConfig.votingCardRequestdeliveryLastTime.person
OK.

2019-05-10 19:49 UTC, KamilZm commented on index.html
> +                    <li><strong class="emphasized">písemně</strong><span> – žádost musíte úřadu doručit do {{this.appConfig.votingCardRequestdeliveryLastTime.post}}h pomocí vaší datové schránky nebo
OK.

2019-05-10 19:49 UTC, KamilZm commented on index.html
> +                    <li><strong class="emphasized">písemně</strong><span> – žádost musíte doručit do {{this.appConfig.votingCardRequestdeliveryLastTime.post}}h pomocí vaší datové schránky nebo poštou
OK, upravím

2019-05-10 19:49 UTC, KamilZm commented on index.html
> +                    <li><strong class="emphasized">in person</strong><span> – directly at the office with valid ID no later than {{this.appConfig.votingCardRequestdeliveryLastTime.personal}}h,</span>
OK, upravím

2019-05-10 19:50 UTC, KamilZm commented on index.html
> +                            {{texts['privacyInfo'][this.getLanguage()]}} <a href="assets/files/Zadost-Volicsky-Prukaz-EU2019-CR.pdf">{{texts['applicationTemplateDownloadLink'][this.getLanguage()]}}</
OK, upravím

2019-05-10 20:07 UTC, KamilZm commented on index.html
> +                    return this.$route.path == '/en/form' ? 'EN' : 'CZ';
Ne, zatím jsem lokalizoval jen část, která je na změny nejcitlivější na změny, protože dokud jsem to neměl lokalizované, tak jsem dělal strašně moc copy&paste chyb. 
Ty další části mají i jiný charakter - jsou to většinou jen texty s interpolací proměnných a tam jsem pro lokalizaci neviděl už tak velké výhody a lokalizovaná verze by vlastně vypadala +- stejně (opět jen text s proměnnými). 
Obecně se tomu nebráním, ale nemělo to pro mě prioritu, protože jsem do toho prakticky nesahal (až na přidání .value).

2019-05-10 20:26 UTC, KamilZm commented
Ke shrnutí: 

Úvodem - nepovažuji to **samozřejmě** za celý refaktor a konečné řešení. Dělal jsem to, co mě nejvíc pálilo a na co byl čas a i na co jsem musel sahat kvůli validacím. 

ad 1 (pull request) - souhlas, chtěl jsem to, ale problém byl, že jsem nepřišel na to, jak udělat další PR, protože dokud jsem měl otevřený jeden, tak jsem neuměl udělat druhý. Commity se automaticky přidávaly k tomu otevřenému.

ad 2) (formáty dat) - asi není větší problém opravit. Zatím jsem tam moc neřešil EN verzi (vzhledem k času), protože tu stejně skoro nikdo používat nebude, viz diskuze ve Slacku. Ten, kdo ji použije, tak to nějak pochopí. Do budoucna jsem to plánoval také předělat.

ad zbytek (validace, částečná lokalizace a předělání 'userData' ze skalárů na objekty s logikou): 
Částečnou lokalizaci jsem ze svého pohledu vysvětlil výše. 

Tahle trojice problémů tvoří 95% tohoto PR. Jak jsem pochopil, tak mé řešení validací se Vám moc nezdá (nepřehledné) , lokalizaci nepreferujete (z Vašeho pohledu přijde výhodnější mít dvě paralelní verze) a změnu v userData zřejmě také ne). Z tohoto pohledu mi teď přijde nejjednodušší to celé, až na konfiguraci 79e260a a scrollování 5e21455 odrolovat, nebo zavřít celý PR, aby se nemusel mergovat s tím, co dělal @woodarius  a ty první dvě změny udělám znovu. 

Jak jsem již psal, dělal jsem to na své triko a zlobit se nebudu. Vy jste šéf a i jste znalostmi v těchto věcech 100x přede mnou.

2019-05-10 20:31 UTC, KamilZm commented on index.html
> +        function getDefaultDataObject(nullable, valid, caption, validator) {
Možná je to jen tím, že neumím Javascript. 

Z původních "obyčejných" property (fullName) se skalárními hodnotami jsem udělal objekty, které mají své vlastnosti (caption, validátor atd.).  a jedna z vlastností je i jeho vlastní hodnota (value). Pokud to jde udělat tak, aby `userData.fullName` obsahovalo skalární hodnotu (to mé dnešní value) a současně mohlo existovat např. `userData.fullName.caption` a metody (`userData.fullName.validate()` atd.), rád to předělám. 

Objekt pro jednu property (fullName, city, ...) vrací funkce `getDefaultDataObject`. Funkce 'getDefaultUserData' pak vrací kompletní objekt pro držení zadaných informací, kde jednotlivé property tvoří právě getDefaultDataObject.

Do funkce `getDefaultUserData` jsem to vyčlenil z důvodu, že se používá na dvou místech (druhé využití je pro vyčištění formuláře, které často používám).

2019-05-10 20:36 UTC, KamilZm commented on index.html
> +                                    max-result-items="15" more-results-exists-text="(...upřesněte zadání...)" ref="autocompleteZIP"
Protože to je uvnitř externí komponenty autocomplete, kterou jsem ještě neučil tento jediný string, který v ní je, přijímat jako atribut. Není problém ji takto upravit, ale zatím jsem to nedělal (nemělo to z mého pohledu takovou prioritu, vzhledem k tomu, že EN verze (zatím) skoro k ničemu není).
Z hlediska index.html platí, že tam není text, který by nebyl lokalizovaný.

2019-05-11 18:57 UTC, KamilZm reviewed
Commit 153c911e obsahuje převážně úpravy z code review:
- formátování datových a časových položek, včetně národnostních verzí. 
- zlepšení některých textů
- oprava lokalizace autocomplete
Dále byly do konfigurace přidány nové položky (název voleb + další data) a byl lokalizován název, který se zobrazuje v hlavičce 

Stále za mě platí od "ad zbytek" do konce [předchozího komentáře](https://github.com/HlidacStatu/Volicsky-Prukaz/pull/74#issuecomment-491419837).

2019-05-12 18:25 UTC, KamilZm reviewed
Na řádcích 338-402 je pouze opraveno odsazení

2019-05-18 15:47 UTC, KamilZm commented
PR po dohodě s @woodarius uzavírám. Provedené úpravy budou znovu vloženy přímo do repo do zvláštní větve (ne přes fork).

2019-05-18 15:47 UTC, closed without merging